### ISSUE TITLE
Lootr chests all display "inventory not loaded"

### ISSUE THREAD

**Issue by mberlin1** [AzureDoom/Modern-s-Monumental-Recipe#1]
Steps to replicate:
Enter the nether, or any new other than spawn
Find a lootr chest
They'll all be empty with the helpful display text "inventory not loaded"

Running the pack in offline mode, no special settings at all, no i'm not in spectator mode.
Stopping and restarting the game has no impact.
I'd be happy to paste a copy of my entire instance, its being run through atlauncher.

**Comment by ModernGamingWorld** [comment]
@mberlin1 This is not an issue tracking for the Modpack, Do not post Modpack issues post them on Bedrocklegends support discord
